name: CI

on:
  push:
    branches:
      - main

env:
  DEPLOY_PATH: /var/www/app
  # В теории можно собрать не только Vue-приложение, так как принцип сборки мало где отличается
  BUILD_SCRIPT: pnpm run build
  BUILD_SCRIPT_OUTPUT: dist

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Делаем checkout текущей ветки
      - uses: actions/checkout@v2
      # Устанавливаем зависимости для сборки
      - name: Install Dependencies
        run: pnpm inpm i
      # Собираем приложение
#       - name: Build Appliction
#         run: $BUILD_SCRIPT
      # Тест
      - name: test
        run: pnpm run serve 

