name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

env:
  DEPLOY_PATH: /var/www/html/
  BUILD_SCRIPT_OUTPUT: dist

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Делаем checkout текущей ветки
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      # Устанавливаем зависимости для сборки
      - name: Install pnpm
        run: npm i -g pnpm
      # Устанавливаем зависимости для сборки
      - name: Install Dependencies
        run: pnpm i
      # Собираем приложение
      - name: Build Appliction
        run: pnpm run build
      # Тест
      - name: Move to www
        run: cp -r ./$BUILD_SCRIPT_OUTPUT/* $DEPLOY_PATH

